name: Build and Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-and-build:
        name: Test and Build
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node-version: [latest, 20, 18]
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Use Node.js latest
              id: setup-node
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Run tests
              run: pnpm test
